### ISSUE TITLE
Add examples folder

### ISSUE THREAD

**Issue by SoaresMG** [Farfetch/react-context-responsive#10]
## Issue Report

We need to have an examples folder for the following scenarios:

- Simple - Using `breakpoints` and `breakpointsMax`
- Dynamic Queries - Passing `mediaQueries` manually

**Comment by joaopedrodcf** [comment]
Should we have a storybook with examples of all this working? Is this your idea? 

I think It also would improve our developer experience when we make changes in the repo and want to visualize them without needing to use thinks like `yarn link` etc.

**Comment by stephan-noel** [comment]
I don't think he's talking about storybook , but just simple written, non-executable examples as there already are in the README.

Storybook seems a bit heavy-handed for a library that has so few exports, but I wasn't able to find any lightweight alternatives.  I  would like to see an interactive fixture of sorts that could help with manual testing similar to what is used in [react's repo](https://github.com/facebook/react/tree/master/fixtures/dom).  Or at the very least, a simple demo like https://contra.io/react-responsive/.

**Comment by SoaresMG** [comment]
We already had an internal talk about creating a separate web app (e.g with storybook), to show all the documentation for Farfetch components.
With this examples folder I was thinking about having at two executable examples:

- With SSR
- With CSR

**Comment by stephan-noel** [comment]
Have you guys heard of [docz](https://github.com/doczjs/docz)?  Maybe it's also a bit too much.  But I like the idea of trying to use `MDX` for executable documentation.

**Comment by joaopedrodcf** [comment]
Looks pretty similar to storybook 🤔

**Comment by stephan-noel** [comment]
yea, but a bit more lightweight and easier to set up.  But maybe we could get by with just simple MDX while we wait for a more complete solution.

**Comment by joaopedrodcf** [comment]
Storybook version 6 is 0 setup from what they say on docs, it even sees your props and automatically creates the controls for it.

**Comment by SoaresMG** [comment]
It was decided that this is out-of-scope and the examples will be created on a separate project that will contain all @farfetch/<> projects
