### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/react-context-responsive#14]
## Issue Report

Would you be in favor of rewriting this library using TypeScript?

**Comment by SoaresMG** [comment]
To me it would be nice to convert everything to TS, we should at least have a `d.ts`

**Comment by joaopedrodcf** [comment]
I would appreciate having the library with TS would improve our development experience in the library and our clients as well. 👍

**Comment by marceloF5** [comment]
It would be nice!

**Comment by SoaresMG** [comment]
Anyone volunteering for this?

**Comment by stephan-noel** [comment]
Yes, I will finish up my other PR and start this.

**Comment by filipesmedeiros** [comment]
Hey guys! What's the status on this? I would love to contribute and can start working on this if you want. I can start refactoring stuff to `.ts` or just create the `.d.ts`s. What do you think?

**Comment by marceloF5** [comment]
@stephan-noel have you been working on it?

**Comment by stephan-noel** [comment]
No, I haven't been, @filipesmedeiros you're more than welcome to take this up!

**Comment by SoaresMG** [comment]
Hey @filipesmedeiros, thank you for the ping on this. We will benefit from a d.ts and that should be enough for TS compability.
In the future we will discuss internally if the project should be refactored to TS or just stay as it is.
