### ISSUE TITLE
Version of the package is not changing in the package.json automatically

### ISSUE THREAD

**Issue by joaopedrodcf** [Farfetch/react-context-responsive#19]
## Issue Report

The version of the package is not changing in the package.json automatically. We are already on version 1.0.2 and in package.json it still stays 1.0.0

## Expected Behavior

Each time a merge to master happens the package.json should be changed automatically.

## Actual Behavior

It isn't changed automatically.

## Steps to Reproduce the Issue

I would say validate [package.json](https://github.com/Farfetch/react-context-responsive/blob/master/package.json) and [changelog](https://github.com/Farfetch/react-context-responsive/blob/master/docs/CHANGELOG.md)

**Comment by SoaresMG** [comment]
The package.json seems to be updated on npm, I guess it's `semantic-release` not doing his job when committing `package.json`.

I will take a look into it
