### ISSUE TITLE
console.log on ResponsiveProvider should not be in a production build

### ISSUE THREAD

**Issue by SoaresMG** [Farfetch/react-context-responsive#22]
## Issue Report

Right now we have some `console.log` to help debug the component.

These logs are wrapped by the following:

```
if (!process || !process.env || process.env.NODE_ENV !== 'test') {
  ...
}
```

If `NODE_ENV` is `production` it will be included in the bundle.

## Expected Behavior

We should exclude those logs when building with `NODE_ENV = "production"`.

To do this, we should follow [webpack's production specs](https://webpack.js.org/configuration/mode/) where they say that when the `mode` is `production` it will automatically call `DefinePlugin` and pass the `mode` to `NODE_ENV`.

So we could end up with something like this:
```
if (process && process.env && process.env.NODE_ENV !== 'production') {
  ...
}
```

When tree shaking happens it will consider that block as "dead code" and not add it to the final bundle.

I also checked if `rollup` was doing something similar and in their official docs they also set an example for `process.env.NODE_ENV = 'production'` as the way to go, you can check it [here](https://rollupjs.org/guide/en/#plugins) and [here](https://rollupjs.org/guide/en/#--environment-values).

## Actual Behavior

Right now those logs end up on the final bundle as you can see here:

![image](https://user-images.githubusercontent.com/8335203/90143468-904b7d80-dd75-11ea-8bec-b3ab995e1a24.png)

## Steps to Reproduce the Issue

Build a web app with the component using webpack or rollup and experiment with `NODE_ENV` at either `development` or `production`

**Comment by joaopedrodcf** [comment]
This makes a lot of sense 💪
