### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by SoaresMG** [Farfetch/react-context-responsive#5]
## Issue Report

Tests are failing due to the modifications made during the migration to github.

## Expected Behavior

- We shouldn't have any tests failling
- New tests should be added regarding the `ResponsiveProvider`

## Actual Behavior

- Most of the tests are failing
- Tests for `ResponsiveProvider` are outdated

## Steps to Reproduce the Issue

Run `yarn test`

**Comment by marceloF5** [comment]
I'll fix this.

**Comment by SoaresMG** [comment]
Closed by #12
