### ISSUE TITLE
New 'mobileBreakpoint' property is not listed in typescript definition file

### ISSUE THREAD

**Issue by billdwhite** [Farfetch/react-context-responsive#51]
## Issue Report

The new 'mobileBreakpoint' property is not listed in typescript definition file and thus displays as an error when used in combination with typescript checking.

## Expected Behavior

The 'mobileBreakpoint' property will not show as an error when typescript checking is applied.

## Actual Behavior

The 'mobileBreakpoint' property shows as an error when typescript checking is applied.

## Steps to Reproduce the Issue

Use the 'mobileBreakpoint' property in a tsx React project and try using the 'mobileBreakpoint' property.  Typescript will complain that the property is not valid.

**Comment by SoaresMG** [comment]
Thank you for your time filling this Issue and creating the PR!

It will be reviewed soon.

**Comment by SoaresMG** [comment]
Hi, the fix was released on [v1.4.0](https://www.npmjs.com/package/@farfetch/react-context-responsive/v/1.4.0)

**Comment by SoaresMG** [comment]
Hi, the fix was released on [v1.4.0](https://www.npmjs.com/package/@farfetch/react-context-responsive/v/1.4.0)
