### ISSUE TITLE
Increase react peer dependency

### ISSUE THREAD

**Issue by mahish** [Farfetch/react-context-responsive#59]
Hi, I just wonder whether there is any reason to keep React 16.9 as a peer dependency instead of current major version 17? I have to `npm update --force` everytime I want to update my projects because of this. Something like this would not work to not break older projects?

```json
"peerDependencies": {
  "react": "^16.9 || ^17"
},
```
  
  Thank you.

**Comment by SoaresMG** [comment]
That's a really good point that we overlooked.

It makes sense to have both `^16.9.0 || ^17.0.0`.

Let's see if all maintainers agree or if there is something I'm missing out.

Unless this could bring unexpected behaviours on newer react versions I see no reason not to change it.

**Comment by dinospereira** [comment]
I agree, I see no reason not to change it to be honest.

**Comment by SoaresMG** [comment]
@mahish are you available to create the PR?

**Comment by mahish** [comment]
@SoaresMG done.
