### ISSUE TITLE
useIsMobile uses hardcoded value

### ISSUE THREAD

**Issue by marceloF5** [Farfetch/react-context-responsive#6]
## Issue Report

`useIsMobile` is using `lessThan.md` as a hardcoded value for the mobile breakpoint.

## Expected Behavior

It should be possible to pass the breakpoint that divides mobile and desktop. 
A solution could be passing that breakpoint as a prop to the provider and consequently to the context.

## Actual Behavior

`useIsMobile` always uses `lessThan.md`

**Comment by sofiacteixeira** [comment]
We need to add a new prop, something like `mobileBreakpoint` and send the breakpoint name (like `md`)

**Comment by SoaresMG** [comment]
It's a good idea! @marcelof5 are you available to drop an PR on it?

**Comment by marceloF5** [comment]
yeah, I can get it!
