### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by SoaresMG** [Farfetch/react-context-responsive#9]
## Issue Report

We need to add some changes on readme, there was some props that weren't added:

- `breakpoints` and `breakpointsMax`
- `mediaQueries`

**Comment by joaopedrodcf** [comment]
Can I take this issue? I need to update the #28 so maybe it would make sense to update everything? What do you guys think?

**Comment by joaopedrodcf** [comment]
Updated the Readme on the #28 with an example of how to setup the `ResponsiveProvider` and also props definition and objects returned by `hooks`, `hocs` and `render props`

https://github.com/Farfetch/react-context-responsive/blob/6d24e97e8ba2d40928d92c5e6358bd73f1bb9377/README.md
